name: swift-android-native ci
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '45 2,13 * * *'
jobs:
  ci:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        # macOS testing isn't strictly necessary
        # os: ['macos-15-intel', 'ubuntu-latest']
        os: ['ubuntu-latest']

        # swift: ['nightly-6.3', 'nightly-main']
        swift: ['nightly-6.3']

        # android-api: ['28', '36']
        android-api: ['28']

        android-ndk: ['r27d', 'r30-beta1']
        # android-ndk: ['r27d']
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Setup Homebrew"
        uses: Homebrew/actions/setup-homebrew@main

      - name: "Build Swift Package for Android (Skip)"
        run: |
          brew install skiptools/skip/skip || (brew update && brew install skiptools/skip/skip)

      - name: "Install Host Toolchain prerequisites"
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install libcurl4-openssl-dev || (sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev)

      - name: "Install Swift SDK for Android"
        run: |
          # need swiftly init on Linux
          swiftly init --assume-yes --no-modify-profile --skip-install
          skip android sdk install --verbose --version ${{ matrix.swift }} --ndk-version ${{ matrix.android-ndk }}
          # https://github.com/swiftlang/swift-driver/pull/1879
          echo "ANDROID_NDK_ROOT=" >> $GITHUB_ENV

      - uses: actions/checkout@v6

      - name: "Build package for Android"
        run: skip android build --build-tests

      - name: "Test Swift Package on Android"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api }}
          arch: x86_64
          script: skip android test --apk --verbose
      - name: "Test Swift Package on host OS"
        run: swift test
      - name: "Test Swift Package on iOS"
        if: runner.os == 'macOS'
        run: xcodebuild test -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 17" -scheme swift-android-native-Package
  soundness:
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      # Not API stable package (yet)
      api_breakage_check_enabled: false
      format_check_enabled: true
      docs_check_enabled: true
